#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/dhh/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/dhh/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/mnt/e/dhh-soltesz-lab/zfish-data/src-parallel/kuramoto_simulation/izhi/x86_64/.libs/libnrnmech.so" "$@"
